# Generated by Django 4.2.6 on 2023-10-21 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название категории')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Нaзвание продукта')),
                ('content', models.TextField(verbose_name='Описание продукта')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='Картинка продукта')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата выполнения')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('price', models.IntegerField(default=0, max_length=15, verbose_name='Цена за продукт')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.category', verbose_name='Категория')),
            ],
        ),
    ]
