# Generated by Django 4.2.6 on 2023-11-11 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_alter_product_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, default='Нет адреса', max_length=100, null=True, verbose_name='Адрес'),
        ),
    ]
