# Generated by Django 4.2.6 on 2023-11-11 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_remove_profile_phone_number_profile_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, default='Нет номера', max_length=40, null=True, verbose_name='Телефонный номер'),
        ),
    ]
