# Generated by Django 4.2.6 on 2023-12-19 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0012_city_customer_order_product_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
