# Generated by Django 4.2.6 on 2023-12-19 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0013_remove_category_slug_remove_product_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaveOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата заказа')),
                ('total_price', models.FloatField(default=0, verbose_name='Сумма заказа')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='market.customer', verbose_name='Покупатель')),
            ],
            options={
                'verbose_name': 'История заказа',
                'verbose_name_plural': 'Истории заказа',
            },
        ),
        migrations.CreateModel(
            name='SaveOrderProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=300, verbose_name='Продукт')),
                ('quantity', models.IntegerField(default=0, verbose_name='Количество')),
                ('product_price', models.FloatField(verbose_name='Цена продукта')),
                ('final_price', models.FloatField(verbose_name='На сумму')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата покупки')),
                ('photo', models.ImageField(upload_to='images/', verbose_name='Фото товара')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='market.saveorder')),
            ],
            options={
                'verbose_name': 'История заказанного товара',
                'verbose_name_plural': 'Истории заказаннфх товаров',
            },
        ),
    ]
